apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: test-app-2
  namespace: test-app-2-prs
spec:
  secretName: test-app-2-tls
  issuerRef:
    name: production-certs
    kind: ClusterIssuer
  dnsNames:
    - '*.test-app-2.beta.hq.powerapp.cloud'
