apiVersion: v1
kind: Namespace
metadata:
  name: default-container-resource-allocations-production
  labels:
    powerapp.cloud/global-registry-access: 'yes'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default-container-resource-allocations-production
imagePullSecrets:
  - name: image-registry-prod-robot-powerhome
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-access
  namespace: default-container-resource-allocations-production
subjects:
- kind: Group
  name: softwareDelivery
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: milano
  namespace: milano-production
roleRef:
  kind: ClusterRole
  name: global:deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: default-container-resource-allocations-production
spec:
  hard:
    pods: "50"
    requests.cpu: "6"
    requests.memory: "8Gi"
    requests.ephemeral-storage: "2Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
    limits.ephemeral-storage: "2Gi"
    configmaps: "40"
    requests.storage: "25Gi"
    persistentvolumeclaims: "20"
    replicationcontrollers: "0"
    secrets: "50"
    services: "30"
    services.loadbalancers: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: default-container-resource-allocations-production
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 100Mi
