apiVersion: v1
kind: Namespace
metadata:
  name: moist-production
  labels:
    powerapp.cloud/global-registry-access: 'yes'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: moist-production
imagePullSecrets:
  - name: image-registry-prod-robot-powerhome
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployment-access
  namespace: moist-production
subjects:
  - kind: Group
    name: softwareDelivery
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: milano
    namespace: milano-production
roleRef:
  kind: ClusterRole
  name: global:deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: moist-production
spec:
  hard:
    pods: 1000
    requests.cpu: 12
    requests.memory: 12Gi
    requests.ephemeral-storage: 
    limits.cpu: 12
    limits.memory: 12Gi
    limits.ephemeral-storage: 5Gi
    configmaps: 1000
    requests.storage: '20Gi'
    persistentvolumeclaims: 10
    replicationcontrollers: 1000
    secrets: 1000
    services: 1000
    services.loadbalancers: 0
