site_name: 'Portal Documentation'
site_description: 'The centralized resource for managing Portal and Portal entities'
nav:
  - Home: index.md
  - "Test Doc": Test Doc.md
plugins:
  - techdocs-core

site_name: 'example-docs'

nav:
  - Home: index.md

plugins:
  - techdocs-core