site_name: 'Portal Documentation'
site_description: 'The centralized resource for managing Portal and Portal entities'
nav:
  - Home: README.md
theme:
  name: material
  font:
    text: Inter
    code: 'JetBrains Mono'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.integrate
extra_css:
  - stylesheets/extra.css
