site_name: 'Hello Root'
site_description: 'I am Root'
nav:
  - 'Intro': index.md
  - 'Component X': '!include ./components/x/mkdocs.yml'
  - 'Component Y': '!include ./components/y/mkdocs.yml'
  - 'Component X': '!include ./components/z/mkdocs.yml'

plugins:
  - monorepo
