apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-real-hello-world-docs
  description: This is a real test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: team-c
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-real-hello-world-docs-component-x
  description: This is a real test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:./components/x
spec:
  type: website
  lifecycle: experimental
  owner: team-c
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-real-hello-world-docs-component-y
  description: This is a real test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:./components/y
spec:
  type: website
  lifecycle: experimental
  owner: team-c
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-real-hello-world-docs-component-z
  description: This is a real test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:./components/z
spec:
  type: website
  lifecycle: experimental
  owner: team-c
