apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-real-hello-world-docs
  description: This is a real test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: team-c
