apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  # This is an extra long description
  description: This is a test of Portal connectivity to Github - test
  annotations:
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/integration-key: f9bec7c325134e00c0af1e640eeaf6c8
spec:
  type: service
  lifecycle: experimental
  owner: team-c
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-component
  title: Test Component
  description: This is a test of Portal connectivity to Github
  links:
    - url: TBD
      title: Portal Production
      icon: public
    - url: https://portal-staging.powerapp.cloud/
      title: Portal Staging
      icon: build
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: web-application
  owner: team-c
  lifecycle: experimental
  system: hello-world
---
apiVersion: backstage.io/v1alpha1
kind: Component2
metadata:
  name: tempo-admin
  title: Tempo Admin
  description: A place for feature toggles, application settings, and other administration related functionality to live.
  links:
    - url: TBD
      title: Test error3
      icon: public
spec:
  type: library
  owner: eternals
  system: tempo
  lifecycle: production
  subcomponentOf: tempo-web
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test-location
  description: Test location
spec:
  targets:
    - ./*/*.yml