apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tempo
  title: Tempo
  description: Loan servicing by Stream Financial
  annotations:
    backstage.io/techdocs-ref: dir:.
    sentry.io/project-slug: tempo
    pagerduty.com/integration-key: 07647e8226dc4e05c0b9952e06ca4f01
    jenkins.io/github-folder: powerhome/tempo
    milano.powerapp.cloud/stack: powerhome/tempo/production
  links:
    - url: https://tempo.streamfinancial.io/
      title: Tempo Production
      icon: public
    - url: https://tempo.staging.streamfinancial.io/
      title: Tempo Staging
      icon: build
    - url: https://tempo.streamfinancial.io/docs
      title: Tempo GraphQL Docs
      icon: public
spec:
  owner: eternals
  lifecycle: production
  domain: stream
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tempo-web
  title: Tempo Web
  description: Tempo Web Application
  annotations:
    sentry.io/project-slug: tempo
    pagerduty.com/integration-key: 07647e8226dc4e05c0b9952e06ca4f01
    jenkins.io/github-folder: powerhome/tempo
spec:
  type: web-application
  owner: eternals
  system: tempo
  lifecycle: production
  providesApis:
    - api:tempo-graphql-api
  dependsOn:
    - resource:tempo-mysql
    - resource:tempo-production-bucket
    - resource:tempo-development-bucket
    - resource:tempo-elasticsearch
    - resource:tempo-openldap
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tempo-subcomponents
  description: Tempo Subcomponent Definitions
spec:
  targets:
    - ./components/*/portal.yml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tempo-graphql-api
  description: Tempo GraphQL
  links:
    - url: https://tempo.streamfinancial.io/docs
      title: Tempo GraphQL Docs
      icon: public
spec:
  type: graphql
  lifecycle: production
  owner: eternals
  system: tempo
  definition: |
    type Query {
      stubbed: String
    }
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-mysql
  description: Tempo's Percona Cluster
  tags:
    - relational
    - mysql
    - pxc
    - percona
spec:
  type: database
  owner: eternals
  system: tempo
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-elasticsearch
  description: Tempo's Elasticsearch Cluster
  tags:
    - search-engine
    - elasticsearch
spec:
  type: database
  owner: eternals
  system: tempo
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-redis
  description: Tempo's HA Redis Cluster
  tags:
    - key-value
    - redis
spec:
  type: database
  owner: eternals
  system: tempo
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-openldap
  description: OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  tags:
    - directory
    - openldap
spec:
  type: database
  owner: eternals
  system: tempo
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-production-bucket
  links:
    - url: s3://s3.powerhrg.com/tempo-production/
      title: S3 URL
      icon: cloudupload
spec:
  type: bucket
  owner: eternals
  system: tempo
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-staging-bucket
  links:
    - url: s3://s3.powerhrg.com/tempo-staging/
      title: S3 URL
      icon: cloudupload
spec:
  type: bucket
  owner: eternals
  system: tempo
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo-devbox-bucket
  links:
    - url: s3://s3.powerhrg.com/tempo-devbox/
      title: S3 URL
      icon: cloudupload
spec:
  type: bucket
  owner: eternals
  system: tempo