apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: hello-world
  title: Hello World
  description: Cool test app
  # annotations:
  #   backstage.io/techdocs-ref: dir:.
spec:
  owner: guardians-of-the-galaxy
  domain: collaboration
  lifecycle: experimental