apiVersion: backstage.io/v1alpha1
kind: Component2
metadata:
  name: tempo-admin
  title: Tempo Admin
  description: A place for feature toggles, application settings, and other administration related functionality to live.
  links:
    - url: TBD
      title: Test error2
      icon: public
spec:
  type: library
  owner: eternals
  system: tempo
  lifecycle: production
  subcomponentOf: tempo-web