apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: has-no-pagerduty
  namespace: has-no-pagerduty-prs
spec:
  secretName: has-no-pagerduty-tls
  issuerRef:
    name: production-certs
    kind: ClusterIssuer
  dnsNames:
    - '*.has-no-pagerduty.beta.gm.powerapp.cloud'
