apiVersion: v1
kind: Namespace
metadata:
  name: TestAppNoReviewEnv-production
  labels:
    powerapp.cloud/global-registry-access: "yes"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: TestAppNoReviewEnv-production
imagePullSecrets:
  - name: quay-robot-powerhome
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployment-access
  namespace: TestAppNoReviewEnv-production
subjects:
- kind: Group
  name: softwareDelivery
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: milano
  namespace: milano-production
roleRef:
  kind: ClusterRole
  name: global:deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: TestAppNoReviewEnv-production
spec:
  hard:
    pods: 1000
    requests.cpu: 6
    requests.memory: 12Gi
    requests.ephemeral-storage: 3Gi
    limits.cpu: 6
    limits.memory: 12Gi
    limits.ephemeral-storage: 3Gi
    configmaps: 1000
    requests.storage: "20Gi"
    persistentvolumeclaims: 3
    replicationcontrollers: 1000
    secrets: 1000
    services: 1000
    services.loadbalancers: 0
