apiVersion: v1
kind: Namespace
metadata:
  name: NewApplicationReviewEnvs-prs
  annotations:
    milano.powerapp.cloud/stack.autoprovision.limit: "1"
  labels:
    powerapp.cloud/global-registry-access: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-template
  namespace: NewApplicationReviewEnvs-prs
data:
  objects.yaml: |
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
    imagePullSecrets:
      - name: quay-robot-powerhome
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: deployment-access
    subjects:
    - kind: Group
      name: appDevelopers
      apiGroup: rbac.authorization.k8s.io
    - kind: ServiceAccount
      name: milano
      namespace: milano-production
    roleRef:
      kind: ClusterRole
      name: global:deployer
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: compute-resources
    spec:
      hard:
        pods: "1000"
        requests.cpu: 4
        requests.memory: 8Gi
        requests.ephemeral-storage: 2Gi
        limits.cpu: 4
        limits.memory: 8Gi
        limits.ephemeral-storage: 2Gi
        configmaps: "1000"
        requests.storage: "20Gi"
        persistentvolumeclaims: 3
        replicationcontrollers: "1000"
        secrets: "1000"
        services: "1000"
        services.loadbalancers: "0"
