apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-component
  title: Test Component
  description: This is a test of Portal connectivity to Github
  links:
    - url: TBD
      title: Portal Production
      icon: public
    - url: https://portal-staging.powerapp.cloud/
      title: Portal Staging
      icon: build
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: web-application
  owner: team-c
  lifecycle: experimental
  system: hello-world