apiVersion: v1
kind: Namespace
metadata:
  name: portal-staging
  labels:
    powerapp.cloud/global-registry-access: "yes"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: portal-staging
imagePullSecrets:
  - name: quay-robot-powerhome
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployment-access
  namespace: portal-staging
subjects:
- kind: Group
  name: softwareDelivery
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: milano
  namespace: milano-staging
roleRef:
  kind: ClusterRole
  name: global:deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: portal-staging
spec:
  hard:
    pods: 1000
    requests.cpu: "6"
    requests.memory: 10Gi
    requests.ephemeral-storage: 2Gi
    limits.cpu: "6"
    limits.memory: 10Gi
    limits.ephemeral-storage: 2Gi
    configmaps: 1000
    requests.storage: "20Gi"
    persistentvolumeclaims: 6
    replicationcontrollers: 1000
    secrets: 1000
    services: 1000
    services.loadbalancers: 0
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
You have unread notifications
