apiVersion: v1
kind: Namespace
metadata:
  name: has-pagerduty-key-prs
  annotations:
    milano.powerapp.cloud/stack.autoprovision.limit: '1'
  labels:
    powerapp.cloud/global-registry-access: 'yes'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-template
  namespace: has-pagerduty-key-prs
data:
  objects.yaml: |
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
    imagePullSecrets:
      - name: image-registry-prod-robot-powerhome
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: deployment-access
    subjects:
    - kind: Group
      name: softwareDelivery
      apiGroup: rbac.authorization.k8s.io
    - kind: ServiceAccount
      name: milano
      namespace: milano-production
    roleRef:
      kind: ClusterRole
      name: global:deployer
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: compute-resources
    spec:
      hard:
        pods: "50"
        requests.cpu: "2"
        requests.memory: "2Gi"
        requests.ephemeral-storage: "300Mi"
        limits.cpu: "2"
        limits.memory: "2Gi"
        limits.ephemeral-storage: "300Mi"
        configmaps: "50"
        requests.storage: "20Gi"
        persistentvolumeclaims: "20"
        replicationcontrollers: "0"
        secrets: "50"
        services: "30"
        services.loadbalancers: "0"
    ---
    apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-resources
    spec:
      limits:
      - type: Container
        default:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 100Mi
        defaultRequest:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 100Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-key-has-pagerduty-key-prs
  namespace: has-pagerduty-key-prs
type: Opaque
stringData:
  key: some-key
---  
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: has-pagerduty-key-prs
  namespace: has-pagerduty-key-prs
  labels:
    alertmanager: monitoring
spec:
  route:
    groupBy:
      - alertname
      - container
      - pod
      - statefulset
      - replicaset
      - daemonset
      - deployment
      - namespace
      - targetName
      - persistentvolumeclaim
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 5m
    receiver: 'pagerduty-has-pagerduty-key-prs'
    continue: false
  receivers:
  - name: pagerduty-has-pagerduty-key-prs
    pagerdutyConfigs:
      - url: https://events.pagerduty.com/v2/enqueue
        severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower }}{{ else }}critical{{ end }}'
        description:
          '[{{ .CommonLabels.cluster }}/{{ .GroupLabels.alertname }}] {{ .CommonAnnotations.description }}'
        routingKey:
          key: key
          name: pagerduty-key-has-pagerduty-key-prs
